setwd("C:\\Users\\Girish.Gore\\Desktop\\RossMan")
library(data.table)
library(zoo)
library(forecast)
library(ggplot2)
library(lubridate)

train <- read.csv("train.csv")
store <- read.csv("store.csv")
test <- read.csv("test.csv")


train$Store <- as.integer(train$Store)
train$DayOfWeek <- as.factor(train$DayOfWeek)
train$Date <- as.Date(train$Date)
train$Week <- as.factor(week(train$Date))
train$Month <- as.factor(month(train$Date))
train$Year <- as.factor(year(train$Date))
train$Open <- as.factor(train$Open)
train$Promo <- as.factor(train$Promo)
train$SchoolHoliday <- as.factor(train$SchoolHoliday)

test$Store <- as.integer(test$Store)
test$DayOfWeek <- as.factor(test$DayOfWeek)
test$Date <- as.Date(test$Date)
test$Week <- as.factor(week(test$Date))
test$Month <- as.factor(month(test$Date))
test$Year <- as.factor(year(test$Date))
test$Open <- as.factor(test$Open)
test$Promo <- as.factor(test$Promo)
test$SchoolHoliday <- as.factor(test$SchoolHoliday)

library(dplyr)
train <- arrange(train, Store, Date)
test <- arrange(test ,  Store ,Date)
train.frame <- forecasting.algorithm(train, test , 'auto.arima')

head(train.frame)
unique(train.frame$Store)
